# Generated by Django 4.2.3 on 2023-07-20 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("appone", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="data_criacao",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
